// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kumhenkknyprvbzagpdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bWhlbmtrbnlwcnZiemFncGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTY5MDksImV4cCI6MjA3MTk3MjkwOX0.c9dBs_CN2VAl9qnByFKNQwov25YSW2JHsDkA-C-cnYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});